Copystatic/admin/config.yml: copy code to clipboard
backend:
  name: github
  repo: silasburger/silas-blog
media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: lang, label: Language, comment: en or es }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }
